# Generated by Django 2.2.5 on 2019-09-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='time_to_close',
            new_name='closing_time',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='time_to_open',
            new_name='opening_time',
        ),
        migrations.AlterField(
            model_name='street',
            name='city',
            field=models.ManyToManyField(related_name='streets', to='shops.City'),
        ),
    ]
